name: CI

on:
  push:
    branches:
    - main
  pull_request:

env:
  # The NAME makes it easier to copy/paste snippets from other CI configs
  NAME: radamsa-sys

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Format
      run: cargo fmt && git diff --exit-code
    - name: Deps
      run: |
        rustup update
        rustup component add clippy
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
    - name: Lint
      run: cargo clippy -- --deny warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
    - run: cargo test --no-run
    - run: cargo test
